name: rawkit • build static libs

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:   [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64 
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"

      - if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build rawkit ${{ matrix.os }} ${{ matrix.arch }}
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            ubuntu*)  bash scripts/build_linux.sh  "${VERSION}" "${{ matrix.arch }}";;
            macos*)   bash scripts/build_darwin.sh "${VERSION}" "${{ matrix.arch }}";;
            windows*) bash scripts/build_windows.sh "${VERSION}" ;;
          esac

      # libs/linux_<arch>/vX.Y.Z/libraw*.a
      - uses: actions/upload-artifact@v4
        with:
          name: libs-${{ matrix.os }}-${{ matrix.arch }}
          path: libs/**/${{ env.VERSION }}/libraw*.a

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Re-assemble repo hierarchy
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME}"
          for f in dist/**/libraw*.a; do
            # dist/libs-ubuntu-latest-amd64/libraw.a
            dir=$(dirname "$f")               # dist/libs-ubuntu-latest-amd64
            osarch=${dir#dist/libs-}          # ubuntu-latest-amd64
            os=${osarch%-latest-*}            # ubuntu
            arch=${osarch##*-}                # amd64
            tgt="libs/${os}_${arch}/${VERSION}"
            mkdir -p "$tgt"
            cp "$f" "$tgt/"
            ln -snf "$VERSION" "libs/${os}_${arch}/current"
          done

      # commit the refreshed current/ symlinks + new versioned dirs
      - name: Commit refreshed libs/current
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update static libs for ${GITHUB_REF_NAME}"
          branch: main
          file_pattern: |
            libs/*/*/current
            libs/*/*/${{ github.ref_name }}/libraw*.a

      # upload assets to the GitHub Release
      - name: Upload static libs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: RawKit ${{ github.ref_name }}
          files: |
            libs/linux_amd64/${{ github.ref_name }}/libraw*.a
            libs/linux_arm64/${{ github.ref_name }}/libraw*.a
            libs/darwin_amd64/${{ github.ref_name }}/libraw*.a
            libs/darwin_arm64/${{ github.ref_name }}/libraw*.a
            libs/windows_amd64/${{ github.ref_name }}/libraw*.a
