name: rawkit • Linux static libs

on:
  push:
    tags:
      - 'v*'            
  workflow_dispatch:    

jobs:
  build:
    name: build-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      
      - name: Export VERSION
        run: echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"

      
      - name: Install build deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential zlib1g-dev
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi

      # ----- build -----
      - name: Build rawkit (${{ matrix.arch }})
        run: ./scripts/build_linux.sh "${VERSION}" "${{ matrix.arch }}"

      
      - name: Upload libraw*.a
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-libs
          path: libs/linux_${{ matrix.arch }}/${{ env.VERSION }}/libraw*.a

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist                              

      - name: List artefacts (debug)
        run: ls -R dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: RawKit ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/linux-amd64-libs/libraw*.a
            dist/linux-arm64-libs/libraw*.a
